### PR TITLE
Add jinglestats command

### PR DESCRIPTION
**Pull request by MattIPv4**
Adds a jinglestats command to the bot - provides some breakdowns (donation per bundle, stats per hour, stats per day).

To test, stub `Date` in `jinglestats/index.js` using:
```javascript
const _Date = Date;
Object.getOwnPropertyNames(Date).forEach(function(name) {
  _Date[name] = Date[name]
});
Date = function() { return arguments.length ? new _Date(...arguments) : new _Date('2020-12-04T00:00:00.000Z') };
Object.getOwnPropertyNames(_Date).forEach(function(name) {
  Date[name] = _Date[name]
});
```

### CODE REVIEW

**Comment by MattIPv4** [comment]
Success:

| Discord | Twitch |
|---|---|
| image | image |

Before bundle launch:

| Discord | Twitch |
|---|---|
| image | image |

Out of season:

| Discord | Twitch |
|---|---|
| image | image |

API broken:

| Discord | Twitch |
|---|---|
| image | image |

**Comment by MattIPv4** [comment]
2020: Tiltify is being used for Jingle Jam this year -- this PR needs to be updated with a data source from them, unsure if they have bundles sold data available (public API only reveals totals donated to each charity)

**Comment by Akhawais** [comment]
Just exposed a `donations_with_reward` field on the jinglejam/api/total API (i.e. bundles sold) - this should help! If you need other metrics let me know.

**Comment by MattIPv4** [comment]
@Akhawais Tyvm! Should be good to go unless you think there should be any copy changes etc.

**Review by Akhawais — APPROVED** [review]

**Comment by Akhawais** [comment]
All looks good to me! Thanks for all your PRs ❤️

**Pull request merged**
